### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by Violetaye** [ShenhanQian/SpeechDrivesTemplates#13]
Your model is fascinating and I would like to test the model, can you provide the file about checkpoint please?
您好！我们对您提出的方法十分感兴趣。我们看一看实现效果，但是没有找到权重在哪里下载，可以提供一下吗？十分感谢！

**Comment by ShenhanQian** [comment]
You can find the link for our checkpoints under this section:
https://github.com/ShenhanQian/SpeechDrivesTemplates/blob/main/README.md#demo

**Comment by Violetaye** [comment]
Thank you！
