### ISSUE TITLE
windows下save_video_in_mp4函数执行至ffmpeg.concat报错解决方案

### ISSUE THREAD

**Issue by liuweie** [ShenhanQian/SpeechDrivesTemplates#14]
First of all, thank the author for replying to me by email and providing me with some solutions. Now that the problem has been solved, provide an issue for reference.

When I reproduce the code to see the demo effect, I run the following command：`python main.py --config_file configs/voice2pose_sdt_bp.yaml --tag luo --demo_input audio1.wav --checkpoint voice2pose_sdt_bp-luo-ep100.pth  DATASET.SPEAKER luo`
The following error occurred：
`FileNotFoundError:[WinError 2]系统找不到指定的文件`

I tried many methods, but still could not run the ffmpeg.concat function correctly. Finally, my solution is as follows (give up using ffmpeg.concat and use other methods)：
![image](https://user-images.githubusercontent.com/86940610/198003913-84db0999-93cf-4ffc-bcb6-9d170ebba53a.png)

**Comment by ShenhanQian** [comment]
Our code was only tested on Ubuntu. And it seems that ffmpeg-python does not fully support Windows. In this case, please consider the above solution.

**Comment by ShenhanQian** [comment]
Our code was only tested on Ubuntu. And it seems that ffmpeg-python does not fully support Windows. In this case, please consider the above solution.
