### ISSUE TITLE
RuntimeError: External code not provide

### ISSUE THREAD

**Issue by liuweie** [ShenhanQian/SpeechDrivesTemplates#15]
I run the following command when I want to test the VAE method demo:`python main.py --config_file configs/voice2pose_sdt_vae.yaml --tag luo  --demo_input audio1.wav --checkpoint checkpoints/voice2pose_sdt_vae-luo-ep100.pth  DATASET.SPEAKER luo
`
Then the following error occured：
`Traceback (most recent call last):
  File "main.py", line 73, in <module>
    main()

  File "main.py", line 69, in main
    run(args, cfg)
  File "main.py", line 45, in run
    pipeline.demo(cfg, exp_tag, args.checkpoint, args.demo_input)
  File "D:\SpeechDrivesTemplates\core\pipelines\trainer.py", line 462, in demo
    self.base_path = self.setup_experiment(False, exp_tag, checkpoint=checkpoint, demo_input=demo_input)
  File "D:\SpeechDrivesTemplates\core\pipelines\trainer.py", line 221, in setup_experiment
    self.setup_model(self.cfg, state_dict=checkpoint['model_state_dict'])
  File "D:\SpeechDrivesTemplates\core\pipelines\voice2pose.py", line 221, in setup_model
    self.model = Voice2PoseModel(cfg, state_dict, self.num_train_samples, self.get_rank()).cuda()
  File "D:\SpeechDrivesTemplates\core\pipelines\voice2pose.py", line 48, in __init__
    raise RuntimeError('External code not provide.')
RuntimeError: External code not provide.`

**Comment by ShenhanQian** [comment]
Our SDT-VAE model relies on the external template vectors from the trained pose VAE. Therefore, you will always need to specify `VOICE2POSE.POSE_ENCODER.AE_CHECKPOINT`. For your case, the following command should work:
```
python main.py --config_file configs/voice2pose_sdt_vae.yaml 
    --tag luo
    --demo_input audio1.wav
    --checkpoint checkpoints/voice2pose_sdt_vae-luo-ep100.pth
    DATASET.SPEAKER luo
    VOICE2POSE.POSE_ENCODER.AE_CHECKPOINT checkpoints/pose2pose-luo-ep100.pth
```

**Comment by liuweie** [comment]
Thanks ，it works.
