### ISSUE TITLE
No audio files in datasets.

### ISSUE THREAD

**Issue by liuweie** [ShenhanQian/SpeechDrivesTemplates#16]
_"To ease later research, we pack our processed data including 2d human pose sequences and corresponding audio clips."_
Hello, I download the dataset from the link you provide,but I found  there is no _audio files_ ,just have _npz files._
Should I generate audio files by myself ? I want to use Luo's data to train model .

**Comment by ShenhanQian** [comment]
You don't need to generate audio data. It's inlcuded in each npz file.

**Comment by liuweie** [comment]
Thanks very much！
