### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by ireneb612** [ShenhanQian/SpeechDrivesTemplates#4]
How do you suggest to create the SPEECH2GESTURE-dataset ?
We need a csv file and a folder with the images? 
Could give some suggestions?

**Comment by ShenhanQian** [comment]
Our data usage follows the setting of the Speech2Gesture datset except that we add face landmarks. You could use their  scripts to process and organize the data. After that, you would get npz files of 2d pose sequences and a csv file for indexing.

**Comment by ireneb612** [comment]
@ShenhanQian What if I would like to use your pretrained models? which speakers should I have in data? all of them?

**Comment by ShenhanQian** [comment]
Inferencing would not rely on the dataset. An input audio clip should be enough.

**Comment by ShenhanQian** [comment]
We've uploaded the dataset.
