### ISSUE TITLE
language dependent

### ISSUE THREAD

**Issue by ireneb612** [ShenhanQian/SpeechDrivesTemplates#5]
Hi, how much do you think the model is language dependent? or do you think it is more dependent on the sound of the audio? Thank you for the checkpoints, I managed to make it work :)

**Comment by ShenhanQian** [comment]
I think the model is more sensitive to the voice than the language because the network works upon the Mel-spectrogram. 

For higher robustness, you may consider data augmentation on the input audio.

**Comment by ireneb612** [comment]
Yes you are right for the gesture, for the lip sinc it get worse, as one could imagine! Maybe I'll try training on my custom speaker, I believe that your work is the best one!
