### ISSUE TITLE
Keypoints format

### ISSUE THREAD

**Issue by Ibrahimatef** [ShenhanQian/SpeechDrivesTemplates#8]
Thanks for your Awesome work!
While generating keypoints using openpose, output format is json file and in your code is npy file.
2_1_gen_kpts.py is not completed yet, Are there instructions to reshape keypoints as required in your script?

**Comment by ShenhanQian** [comment]
Hi @Ibrahimatef, we have updated `2_1_gen_kpts.py` for your reference:
https://github.com/ShenhanQian/SpeechDrivesTemplates/blob/c1e1b6ddd65456c3d31fb71f788c30ffd09a2e92/data_preprocess/2_1_gen_kpts.py#L49-L54
